# Generated by Django 5.1.4 on 2026-02-14 21:19

import django.utils.timezone
import recurrence.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('is_special', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now, help_text='Start date of the event.')),
                ('recurrence', recurrence.fields.RecurrenceField(blank=True, help_text='Set recurrence rules for the event. Leave empty for one-time events.', null=True)),
                ('start_time', models.TimeField(default=django.utils.timezone.now, help_text='Start time of the event.')),
                ('end_time', models.TimeField(default=django.utils.timezone.now, help_text='End time of the event.')),
                ('location', models.CharField(help_text='Location of the event.', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
