# Generated by Django 6.0.2 on 2026-02-09 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_add_timestamps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='event',
        ),
        migrations.DeleteModel(
            name='QRCodeToken',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
