# Generated by Django 6.0.2 on 2026-02-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The question being asked')),
                ('is_anonymous', models.BooleanField(default=True, help_text='Whether the question is anonymous')),
                ('submitter_name', models.CharField(blank=True, help_text='Name of the person asking (if not anonymous)', max_length=100, null=True)),
                ('submitter_email', models.EmailField(blank=True, help_text='Email of the person asking (optional)', max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='questions_q_created_d1d888_idx')],
            },
        ),
    ]
