# Generated by Django 6.0.2 on 2026-02-15 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_anonymous',
        ),
        migrations.RemoveField(
            model_name='question',
            name='submitter_email',
        ),
        migrations.RemoveField(
            model_name='question',
            name='submitter_name',
        ),
    ]
